<?php
/**
 * API模块下共用控制器 如果无需登录场景集成此控制器
 * create by XinyuLi
 * @since 10/06/2020 19:44
 */

namespace app\api\controller;
use app\BaseController;
use think\exception\HttpResponseException;

class ApiBase extends BaseController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function show(...$args){
        throw new HttpResponseException(show(...$args));
    }
}